# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


workflows:
  build-project:
      jobs:
        - build-and-test

jobs:  
  build-and-test:
    macos:
      xcode: 14.0.0
    steps:
      - checkout
      - run: xcodebuild -version
      - run:
          name: list files
          command: ls -a
      - run:
          name: install xcbeautify
          command: brew install xcbeautify
      - run:
          name: test
          command: xcodebuild -project DummyApp.xcodeproj -scheme DummyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' test | xcbeautify
